/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/login/complete-profile" |
       "/pages/login/index" |
       "/pages/mine/index" |
       "/pages/mine/about/index" |
       "/pages/mine/faq/index" |
       "/pages/mine/feedback/index" |
       "/pages/mine/profile/index" |
       "/pages/mine/settings/index" |
       "/pages/mine/settings/account/index" |
       "/pages/mine/settings/agreement/index" |
       "/pages/mine/settings/network/index" |
       "/pages/mine/settings/privacy/index" |
       "/pages/mine/settings/theme/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
