/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/login/index" |
  "/pages/mine/index" |
  "/pages/webview/index" |
  "/pages/work/index" |
  "/pages/mine/about/index" |
  "/pages/mine/account/index" |
  "/pages/mine/official/index" |
  "/pages/mine/profile/complete-profile" |
  "/pages/mine/profile/index" |
  "/pages/mine/scan-confirm/index" |
  "/pages/mine/settings/index" |
  "/pages/work/config/index" |
  "/pages/work/dept/index" |
  "/pages/work/dict/index" |
  "/pages/work/log/index" |
  "/pages/work/menu/index" |
  "/pages/work/monitor/index" |
  "/pages/work/notice/index" |
  "/pages/work/role/assign-perm" |
  "/pages/work/role/index" |
  "/pages/work/user/index" |
  "/pages/mine/settings/agreement/index" |
  "/pages/mine/settings/network/index" |
  "/pages/mine/settings/privacy/index" |
  "/pages/mine/settings/theme/index" |
  "/pages/work/dict/item/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/work/index" | "/pages/mine/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
